# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ReactNativeCodePattern' do
  #use_frameworks!

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'jschelpers',
      'cxxreact',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTImage',
      'RCTNetwork',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTWebSocket', # needed for debugging
      'DevSupport',
      # Add any other subspecs you want to use in your project
    ]

  #pod 'React', path: '../node_modules/react-native'
  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'RNIBMMobileFirst', path: '../node_modules/react-native-ibm-mobilefirst/ios'

  pod 'RNIBMMobileFirst', :path => '../node_modules/react-native-ibm-mobilefirst/ios', :subspecs => [
    'RNMFP'
  ]

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

end
